import { useState, useEffect } from 'react'
import { getFlag, pct } from '../utils/helpers'

export default function AnalysisModal({ analysis, onClose }) {
  const [displayedText, setDisplayedText] = useState('')
  const [done, setDone] = useState(false)

  // Typewriter effect
  useEffect(() => {
    const text = analysis.narrative || ''
    let i = 0
    setDisplayedText('')
    setDone(false)
    const interval = setInterval(() => {
      i++
      setDisplayedText(text.slice(0, i))
      if (i >= text.length) { clearInterval(interval); setDone(true) }
    }, 18)
    return () => clearInterval(interval)
  }, [analysis.narrative])

  const s = analysis.stats || {}

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-box fade-in" onClick={e => e.stopPropagation()}>
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1.5rem' }}>
          <div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 4 }}>AI Match Preview</div>
            <h3 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <span>{getFlag(analysis.team_a)}</span>
              <span>{analysis.team_a}</span>
              <span style={{ color: 'var(--text-muted)', fontWeight: 400 }}>vs</span>
              <span>{analysis.team_b}</span>
              <span>{getFlag(analysis.team_b)}</span>
            </h3>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: 'var(--text-muted)', fontSize: '1.4rem', cursor: 'pointer', lineHeight: 1 }}>×</button>
        </div>

        {/* Narrative */}
        <div style={{
          background: 'rgba(245,158,11,0.05)', border: '1px solid var(--border-gold)',
          borderRadius: 'var(--radius-md)', padding: '1.2rem', marginBottom: '1.5rem',
          fontSize: '0.95rem', lineHeight: 1.8, color: 'var(--text-primary)',
          minHeight: 80
        }}>
          {displayedText}
          {!done && <span className="typewriter-cursor" />}
        </div>

        {/* Stats grid */}
        {s.home_win_prob !== undefined && (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.75rem' }}>
            {[
              { label: analysis.team_a, value: pct(s.home_win_prob), color: 'var(--green)' },
              { label: 'Draw',          value: pct(s.draw_prob),     color: 'var(--text-secondary)' },
              { label: analysis.team_b, value: pct(s.away_win_prob), color: 'var(--red)' },
              { label: `${analysis.team_a} Elo`, value: s.elo_a, color: 'var(--gold)' },
              { label: `${analysis.team_b} Elo`, value: s.elo_b, color: 'var(--gold)' },
              { label: 'Confidence',    value: s.confidence?.toUpperCase(), color: 'var(--blue)' },
            ].map(({ label, value, color }) => (
              <div key={label} style={{ background: 'rgba(255,255,255,0.03)', borderRadius: 'var(--radius-sm)', padding: '0.75rem', textAlign: 'center' }}>
                <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', marginBottom: 4, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{label}</div>
                <div style={{ fontWeight: 700, fontSize: '1.05rem', color }}>{value}</div>
              </div>
            ))}
          </div>
        )}

        <p style={{ fontSize: '0.72rem', color: 'var(--text-muted)', marginTop: '1rem', textAlign: 'center' }}>
          ✨ Generated by GPT-4o-mini using historical match data & Elo ratings
        </p>
      </div>
    </div>
  )
}
